drd_pi_pantheon.pantheon_account.*:
  type: config_entity
  label: 'Pantheon account config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    machine_token:
      type: string
      label: 'Machine Token'
