drd_pi_acquia.acquia_account.*:
  type: config_entity
  label: 'Acquia account config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    email:
      type: string
      label: 'E-mail'
    private_key:
      type: string
      label: 'Private key'
