drd.script_type.*:
  type: config_entity
  label: 'Script Type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    interpreter:
      type: string
      label: 'Interpreter'
    extension:
      type: string
      label: 'Extension'
    prefix:
      type: string
      label: 'Prefix'
    suffix:
      type: string
      label: 'Suffix'
    lineprefix:
      type: string
      label: 'Line prefix'
