drd.script_code.*:
  type: config_entity
  label: 'Script config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    type:
      type: string
      label: 'Type'
    code:
      type: string
      label: 'Code'
