field.storage_settings.key_value:
  type: mapping
  mapping:
    key_max_length:
      type: integer
      label: Key maximum length
    key_is_ascii:
      type: boolean
    max_length:
      type: integer
      label: Max length
    is_ascii:
      type: boolean
    case_sensitive:
      type: boolean

field.field_settings.key_value:
  type: mapping
  mapping: {}

field.value.key_value:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'
    key:
      type: string
      label: 'Key'

field.widget.settings.key_value_textfield:
  type: field.widget.settings.string_textfield
  label: 'Key / Value (multiple rows)'
  mapping:
    key_size:
      type: integer
      label: 'Size of key textfield'
    key_placeholder:
      type: string
      label: 'Key placeholder'
    description_enabled:
      type: boolean
      label: 'Description enabled'
    description_placeholder:
      type: string
      label: 'Description placeholder'

field.storage_settings.key_value_long:
  type: mapping
  mapping:
    key_max_length:
      type: integer
      label: Key maximum length
    key_is_ascii:
      type: boolean

field.field_settings.key_value_long:
  type: mapping
  mapping:
    default_format:
      type: string
      label: Default text format

field.value.key_value_long:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'
    key:
      type: string
      label: 'Key'
    format:
      type: string
      label: 'Format'

field.widget.settings.key_value_textarea:
  type: field.widget.settings.string_textarea
  label: 'Key / Value (multiple rows)'
  mapping:
    key_size:
      type: integer
      label: 'Size of key textfield'
    key_placeholder:
      type: string
      label: 'Key placeholder'
    description_enabled:
      type: boolean
      label: 'Description enabled'
    description_placeholder:
      type: string
      label: 'Description placeholder'

field.formatter.settings.key_value:
  type: mapping
  label: 'Key / Value'
  mapping:
    value_only:
      type: boolean
      label: 'Value only'
